process.env.DB_USER='thomas'
process.env.DB_HOST='localhost'
process.env.DB_DATABASE='thomas'
process.env.DB_PASSWORD='password'
process.env.PORT='3000'
process.env.JWT_SECRET='jwt_aqa_secret'
process.env.SESSION_SECRET='session_aqa_secret'
